host         : 0.0.0.0
markdown_ext : "markdown,mkdown,mkdn,mkd,md,html"

compress_html:
  comments: ["<!-- ", " -->"]

themes:
  - 'mario-yellow'
  - 'mario-red'
  - 'mario-blue'
  - 'mario-green'
  - 'light'
  - 'dark'
  - 'discord'
  - 'default'

defaults:
  - scope:
      path: "/"
      type: pages
    values:
      permalink: /:basename:output_ext
      layout: "default"
